### ISSUE TITLE
Upgrade to L4T 32.1

### ISSUE THREAD

**Issue by Davidnet** [balena-os/balena-jetson-skx2#125]
With the new release of Jetpack 4.2 as official, do you guys think that it would be possible to upgrade the image to use L4T 32.1.

Thanks

**Comment by floion** [comment]
Hi, we'll have this in our to-do list

**Comment by vicgal** [comment]
Hello,

BalenaOS uses the meta-tegra from here: https://github.com/madisongh/meta-tegra. In this layer support for L4T 32.1 is added for the Thud and Warrior versions (and the branches are marked with "work in progress") and meta-balena only supports up till and including sumo. You can track the progress of adding Poky support for Thud and Warrior in these 2 issues:
https://github.com/balena-os/meta-balena/issues/1313
https://github.com/balena-os/meta-balena/issues/1458

**Comment by sjdrc** [comment]
`master` and `warrior` branches now support R32.1 https://github.com/madisongh/meta-tegra/issues/128

**Comment by floion** [comment]
We need warrior support in meta-balena for this. There is an open ticket for that in meta-balena, work on that should happen soon

**Comment by compiaffe** [comment]
@floion Are there any news on L4T 32.x support?

**Comment by floion** [comment]
Hi @compiaffe we have a branch for this working but we cannot yet release it because there are some issues with the host OS update because of some issue that NVidia is supposed to fix in their bootloader. So we are expecting a new release from NVidia before we release L4T 32.x or newer

**Comment by sjdrc** [comment]
Hey @floion do you have any more details on the bootloader issue?

**Comment by floion** [comment]
@sjdrc see https://github.com/madisongh/meta-tegra/issues/134 and https://devtalk.nvidia.com/default/topic/1054833/jetson-tx2/jetpack-4-2-partitions-size-odd-behavior/

**Comment by compiaffe** [comment]
@floion I see this is a wontfix for the R32.1 L4T release. Will there be some form of workaround or are you waiting for a fix/newer release?

**Comment by floion** [comment]
Hi this will be fixed by L4T-r32.2 which we're expecting to support in the near future

**Comment by compiaffe** [comment]
@floion any progress on this?

**Comment by floion** [comment]
Hi @compiaffe we have it working here https://github.com/balena-os/balena-jetson but not yet deployed due to some supervisor feature we need to have for this.

**Comment by compiaffe** [comment]
Hi @floion  good to hear. What features are missing? 
I just build it manually, what can I expect to not work?

**Comment by Davidnet** [comment]
@compiaffe I think that you will not have any problem, mainly I think is that due to how supervisor is implemented and the mess of Nvidia breaking packages from 28 to 32, they are integrating a feature on supervisor so that we can select which L4T and avoid having breaking OS updates

**Comment by floion** [comment]
@compiaffe if you build it and deploy on new machines, it will work as expected. It will be only problematic for host OS updates from older versions as you will also need to rebuild your user containers for the new OS.
It is just as @Davidnet said above, we need a way to not let users be affected by the breaking changes nVidia introduced with the L4T updates. The feature is being worked at the moment, I don't have an ETA for it at this point.

**Comment by compiaffe** [comment]
Thanks, that answers my question.

**Comment by acostach** [comment]
Closing this issue since 32.2 is now available for jetson-tx2 device type in production dashboard at BalenaOS 2.47.0+rev2
