### ISSUE TITLE
Specifying custom PINMUX and PMC

### ISSUE THREAD

**Issue by sjdrc** [balena-os/balena-jetson-skx2#168]
For the blackboard TX2 carrier, when flashing with nvidia's Linux4Tegra driver package, I have to specify custom PINMUX_CONFIG and PMC_CONFIG variables pointing to my own generated files. How can I include support for these custom requirements in balena?

**Comment by acostach** [comment]
@sjdrc I think you could try adding them separately as SRC_URI_append_blackboard in tegra186-flash-dry and then override the generic tx2 ones with blackboard's, right before they are being used: https://github.com/balena-os/balena-jetson-skx2/blob/d9b3ef39e5786d37576ff581dbde422fcda85bc3/layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_28.3.0.bb#L140
https://github.com/balena-os/balena-jetson-skx2/blob/d9b3ef39e5786d37576ff581dbde422fcda85bc3/layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_28.3.0.bb#L142
Please note that you need to use either HUP or SD-card to flash the board with your generated image for testing.

**Comment by acostach** [comment]
Closing this for now since it was not an issue but a question, which has been answered. If there are any custom changes needed for pinmux, please feel free to PR them.
