### ISSUE TITLE
Getting: Invalid volume signature! for jetson-tx2/2.13.0+rev1 using "resin local configure"

### ISSUE THREAD

**Issue by ofirule** [balena-os/balena-jetson-skx2#72]
Not sure who should handle it.
Please view:
https://github.com/resin-io/resin-cli/issues/908

**Comment by floion** [comment]
Hi, is this still an issue for you?

**Comment by ofirule** [comment]
It was fixed in the cli

**Comment by floion** [comment]
Thanks for the notice.
