### ISSUE TITLE
Spacely Build Fails

### ISSUE THREAD

**Issue by chachi** [balena-os/balena-jetson-skx2#81]
When running `./resin-yocto-scripts/build/barys -d -m spacely-tx2` on both master and tag `v2.14.1+rev1`, the build failed with

```
| Error: Return value 4
| Command tegrahost_v2 --chip 0x18 --partitionlayout flash.xml.bin --list images_list.xml zerosbk
| Keep temporary directory /data/jack/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/tegra186-flash-dry/28.2.0-r0/build/17551
| /data/jack/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/tegra186-flash-dry/28.2.0-r0/build
| cat: /data/jack/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/tegra186-flash-dry/28.2.0-r0/build/out/br_bct_BR.bct: No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /data/jack/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/tegra186-flash-dry/28.2.0-r0/temp/log.do_compile.17381)
ERROR: Task (/data/jack/resin-jetson-tx2/build/../layers/meta-resin-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_28.2.0.bb:do_compile) failed with exit code '1'
```

**Comment by dwalkes** [comment]
Same failure here running
`
./resin-yocto-scripts/build/barys -m jetson-tx2
`
on master

**Comment by c-wilson** [comment]
I made some progress on a workaround for this. The missing file that's causing compilation of tegra186-flash-dry to fail is a broken symlink:

`./build/tmp/work/aarch64-poky-linux/tegra186-flash-dry/28.2.0-r0/build/u-boot-dtb.bin -> ./build/tmp/deploy/images/jetson-tx2/u-boot-dtb.bin`

It looks like `u-boot-dtb.bin` is not copied into the deploy/images folder at the time when `tegra186-flash-dry:do_compile` is running. It seems like it is generated though. After the failure described above, copying u-boot-dtb.bin` manually and rerunning `barys` allows the build to complete.

`cp ./build/tmp/work/jetson_tx2-poky-linux/u-boot-tegra/2016.07+gitAUTOINC+89f0003c0b-r0/build/u-boot-dtb.bin /build/tmp/deploy/images/jetson-tx2/`

I don't understand why this behavior is occurring, though. I am running a pretty clean Ubuntu 16.04 install and all dependancies are standard versions installed from apt.

**Comment by floion** [comment]
Hi, it this still an issue for you? Can we close this ticket?

**Comment by chachi** [comment]
We’re no longer testing this so I’m not sure if it’s still broken or not
but isn’t a concern for me.

**Comment by floion** [comment]
Thanks for the follow-up.

**Comment by ElmarSieke** [comment]
balena-jetson-skx2: commit 13bd883d4caabd932dce05d325ad0be03f71103c  
  
Had the same issue!  
To finish the build i did the following:  
```bash
cp ./build/tmp/work/jetson_tx2-poky-linux/u-boot-tegra/2016.07+gitAUTOINC+1fe11f4336-r0/build/u-boot-dtb.bin ./build/tmp/deploy/images/jetson-tx2/
./balena-yocto-scripts/build/barys -m jetson-tx2
rm ./build/tmp/deploy/images/jetson-tx2/u-boot-dtb.bin 
./balena-yocto-scripts/build/barys -m jetson-tx2
```




build host uname: Linux f21b7ded3c9b 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 x86_64 x86_64 GNU/Linux
